import type { Metadata } from "next";
import Header from "./components/static/Header";
import Footer from "./components/static/Footer";
import { poppins} from "./utils/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen bg-[#FAFAFA] ${poppins.className}`}>
      <Header />
      <main className="flex-grow">
        {children}
      </main>
      <Footer />
    </body>
    </html>
  );
}
