import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/static/Header";
import Footer from "./components/static/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-[#FAFAFA]">
      <Header />
      <main className="flex-grow">
        {children}
      </main>
      <Footer />
    </body>
    </html>
  );
}
